name: manifest_validation

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Validating manifest
      run: |
        python -m pip install --upgrade pip
        make validate_manifest PYTHON=`which python`
